### ISSUE TITLE
Var Let Const in JAVASCRIPT

### ISSUE THREAD

**Issue by tenaiti** [truongduchuy910/TechDra#33]
VAR : Biến var sẽ có scope là globally scoped. Và biến var có tính chất hoisting: nghĩa là khai báo ở đâu khi thực thi đều được dịch đầu tiên. Khai báo bằng var mà không nhận giá trị thì mặc định sẽ nhận giá trị khởi tạo là undefine. Nếu khai báo tiếp thì biến đó sẽ cập nhật giá trị mới.
LET : Biết let sẽ có scope là block scoped. Thường được dùng trong các block scoped như if for...Và biến chỉ tồn tại trong block scoped đó. Biến let chỉ được cho biến cập nhật giá trị mới nhưng không được tái khai báo biến.
vd: let ten = 10; // ten = 10;
           ten = 5; // ten =5;
còn tính hoisting tương tự như var.
CONST : cũng tương tự như let nhưng const sẽ chỉ nhận một giá trị đầu tiên sơ khai. Khai báo const mà không có giá trị sẽ bị lỗi Reference Error.

**Comment by baphuc2906** [comment]
good :V

**Comment by tenaiti** [comment]
ló là phải thế :D

**Comment by nhantruong2712** [comment]
cc

**Comment by tenaiti** [comment]
Con cặc

Vào Th 7, 14 thg 9, 2019 lúc 21:07 nhantruong2712 <notifications@github.com>
đã viết:

**Comment by baphuc2906** [comment]
> cc

thèn vô văn hóa. t có súng đó nge

**Comment by truongduchuy910** [comment]
Không cần viết ra đâu, tên bài với link đồ sương sương được rồi
