### ISSUE TITLE
Function context & bind in JAVASCRIPT

### ISSUE THREAD

**Issue by tenaiti** [truongduchuy910/TechDra#36]
ví dụ : mình có 1 cái object tên là cat với các thuộc tính như trên.
```
cat = {
   name : 'Tom',
   color : 'yellow',
   sayHi : function(){
           console.log(' Chao meo' , this.name); 
          }
}
```
bình thường nếu gọi thuộc tính sayHi chúng ta sẽ:
`cat.sayHi(); //Chao meo Tom`
nhưng nếu ta khai báo một cái biến
```
var say = cat.sayHi;
say(); // Chao meo undefined
```
bởi vì this.name nó không thể xác định được. Giờ ta muốn nó xác định thì phải dùng như sau:
```
var say = cat.sayHi.bind(cat);
say(); //Chao meo Tom
```
lúc này khi hàm say được gọi thì this sẽ được hiểu là cat.name.

**Comment by trunglv2000** [comment]
ghê vcl :v
