### ISSUE TITLE
Trừu tượng, Đóng gói, Kế thừa và Đa hình trong OOP

### ISSUE THREAD

**Issue by cuongnguyen99** [truongduchuy910/TechDra#38]
Link bài học: 
https://drive.google.com/file/d/1RlPfoBpSx-9SJgCOx0EZhM5oBeedJ_hJ/view?usp=sharing
https://drive.google.com/file/d/12oSHnHlZqHiNfxc6264Doqja4rLrx4E5/view?usp=sharing
https://drive.google.com/file/d/1wZft9cF4OAZJjCVHEMOMJhnJHTH2YzaO/view?usp=sharing
https://drive.google.com/file/d/10tQlrj2Vx2jqpRZtg7muBPt1_L8b-q9Y/view?usp=sharing

**Comment by tenaiti** [comment]
thanks!

**Comment by cuongnguyen99** [comment]
> thanks!
no problems

**Comment by truongduchuy910** [comment]
Bạn cương siêng tạo issue lên hỉ
