### ISSUE TITLE
Học tham chiếu và review ít kiến thức về class(private, public) trong giáo trình cô Hạnh

### ISSUE THREAD

**Issue by NguyenVu124** [truongduchuy910/TechDra#39]
[Tham chiếu và sự khác nhau với con trỏ](https://drive.google.com/file/d/1R8CnHq0EFqn7-r3LZcAORhTwT-VN0s--/view?usp=sharing)
// 1. Tham chiếu phải khởi tạo giá trị khi khai báo. (Con trỏ khởi tạo lúc nào cũng được)
// 2. Tham chiếu không NULL được.

Review về private và public:
- Bất kỳ thành viên dữ liệu hay hàm thành viên khai báo sau public có thể được truy cập bất kỳ nơi nào mà chương trình truy cập đến một đối tượng của lớp.
- Bất kỳ thành viên dữ liệu hay hàm thành viên khai báo sau private chỉ có thể được truy cập bởi các hàm thành viên của lớp.

**Comment by baphuc2906** [comment]
2. tham chiếu không NULL được là sao?

**Comment by NguyenVu124** [comment]
ví dụ bên con trỏ có khai báo int* p=NULL thì đc, bên tham chiếu khai báo int& k=NULL thì báo lỗi
