### ISSUE TITLE
Vòng lặp while loop + làm bt

### ISSUE THREAD

**Issue by nhantruong2712** [truongduchuy910/TechDra#55]
https://www.howkteam.vn/course/lap-trinh-python-co-ban/vong-lap-while-trong-python-2595

**Comment by tenaiti** [comment]
làm bài tập là show ra :)

**Comment by nhantruong2712** [comment]
Zô link xem, show cc

**Comment by tenaiti** [comment]
Làm việc phải professional

Vào CN, 15 thg 9, 2019 lúc 00:40 nhantruong2712 <notifications@github.com>
đã viết:

**Comment by cuongnguyen99** [comment]
Đề nghị bạn nhân để ảnh đại diện cho mọi người nhận dạng
