### ISSUE TITLE
Hàm và tạo hàm (function) trong javascript

### ISSUE THREAD

**Issue by phuong15032000** [truongduchuy910/TechDra#62]
https://freetuts.net/ham-va-tao-ham-function-trong-javascript-274.html

**Comment by phuong15032000** [comment]
Tạm dừng học js để học OOP

**Comment by truongduchuy910** [comment]
OOP cũng có thẻ "Lập Trình Hướng Đối Tượng"
Nhớ gắn label cho issue

**Comment by truongduchuy910** [comment]
Cái nào liên quan đến web thì gắn thẻ là MERN Stack hỉ
