### ISSUE TITLE
Khai báo Class trong C++

### ISSUE THREAD

**Issue by cuongnguyen99** [truongduchuy910/TechDra#63]
class <tên class>{
Khai báo thuộc tính.
Khai báo phương thức.
(private,  public, protected)
       +)  private: chỉ được sử dụng bên trong class, các hàm bên ngoài không truy cập được
       +) public: hàm khác bên ngoài class có thể truy cập được
}
- Cách khởi tạo một đối tượng: <tên class> <tên đối tượng>;
- Cách truy cập đến 1 thành phần của  class: <tên đối tượng>.<phương thức or thuộc tính>;
Vd: 
class DT3{
        private:
                string Hoten;
        public:
                string Tenho;
}
int main()
{
      DT3 Hocsinh;
      Hocsinh.Tenho;
}

**Comment by cuongnguyen99** [comment]
cách hiểu nôm na của mình là vậy, ai có bổ sung gì thì comment để góp ý sửa sai...

**Comment by NguyenVu124** [comment]
t review thêm tí là nhớ quy tắc đặt tên các thuộc tính(viết hoa chữ cái đầu của mỗi chữ)

**Comment by cuongnguyen99** [comment]
> t review thêm tí là nhớ quy tắc đặt tên các thuộc tính(viết hoa chữ cái đầu của mỗi chữ)

Nếu ko viết hoa là nó báo lỗi à?
