### ISSUE TITLE
Hàm phá hủy (destructor) & Thành viên tĩnh (static member)

### ISSUE THREAD

**Issue by NguyenVu124** [truongduchuy910/TechDra#64]
- Destructor:
    // Destructor, được gọi ngay trước khi một đối tượng bị thu hồi
    // Destructor thường được dùng để thực hiện việc dọn dẹp cần thiết trước khi một đối tượng bị hủy
    // Một lớp chỉ có duy nhất một Destructor
    // Phương thúc Destructor trùng tên với tên lớp nhưng có dấu ~ đặt trước
    // Được tự dộng gọi thực hiện khi đối tượng hết phạm vi sử dụng
    // Destrutor phải có thuộc tính public
Ví dụ: HocSinh();  // phuong thuc khoi tao mac dinh
	~HocSinh();  //phuong thuc pha huy

- Static member:
    // Một bản duy nhất tồn tại trong suốt quá trình chạy
    // Dùng chung cho tất cả các đối tượng của lớp. Bất kể có bao nhiêu đối tượng được tạo ra từ class đó
    // Phải được định nghĩa bên ngoài class vì thành viên tĩnh được lưu trữ riêng biệt, không giống các thành phần khác của đối tượng
    // Giá trị khởi tạo =0 và có thể gán giá trị khởi tạo
Ví dụ:
  #include<iostream>
using namespace std;

class PhanSo
{
private:
	// Khai bao thanh phan Static
	static int dem;
	int TuSo, MauSo;
public:
	PhanSo()
	{
		TuSo = 0;
		MauSo = 1;
	}
	// truyen vao 2 tham so
	PhanSo(int tu, int mau)
	{
		TuSo = tu;
		MauSo = mau;
		dem++;
	}
	void XemGiaTri()
	{
		cout << dem << endl;
	}
	~PhanSo()
	{
	}
};
// cai dat
int PhanSo::dem; //ko gan gia tri (hoac gan gia tri)
int main()
{
	// neu ko phai ban duy nhat: ps1(dem), ps2(dem)
	PhanSo ps1(2, 3), ps2(3, 4), ps3(4, 5);
	ps1.XemGiaTri();
	//ps2.XemGiaTri();
	system("pause");
	return 0;
}

**Comment by truongduchuy910** [comment]
Khai báo
int x;
static int x;
cùng lúc như thế này thì có lỗi không? vì sao lỗi

**Comment by NguyenVu124** [comment]
Sẽ báo lỗi, biến đã được khai báo thì không cho phép khai báo lại thành static member
