### ISSUE TITLE
Khai báo phương thức C++

### ISSUE THREAD

**Issue by cuongnguyen99** [truongduchuy910/TechDra#68]
#include <iostream>
#include <string>
using namespace std;
class DT3
{
	private:
		string Hoten;
		string Que;
		int DiemTB;
	public:
		void Nhap();
		void Xuat();
		
};
void DT3::Nhap()
{
	cout <<"Nhap ho va ten: ";
	fflush(stdin);
	getline(cin, Hoten);
    cout <<"\nNhap que quan: ";
    fflush(stdin);
    getline(cin, Que);
    cout <<"\nNhap diem trung binh: ";
    cin >> DiemTB;
}
void DT3::Xuat()
{
	cout <<"Ho ten: " <<Hoten;
	cout <<endl << "Que quan: " <<Que;
	cout << endl << "Diem trung binh: " <<DiemTB;
}
int main()
{
	DT3 Hocsinh;
	Hocsinh.Nhap();
	Hocsinh.Xuat();
	return 0;
}

**Comment by cuongnguyen99** [comment]
Các bạn cũng có thể khai báo trực tiếp ngay trong "class"

**Comment by truongduchuy910** [comment]
Bạn Cương vào đọc markdown in Github nhà
ví dụ code thì để giữa 3 dấu nháy là nó sẽ hiển thị ra.
``` C
int main()
{
    DT3 Hocsinh;
    Hocsinh.Nhap();
    Hocsinh.Xuat();
    return 0;
}
```
